version: '3.9'

services:
  node:
    container_name: sequelize_mysql_express_javascript_app_node
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    networks:
      - sequelize_mysql_express_javascript_app
    volumes:
      - ./:/usr/app

  mysql:
    container_name: sequelize_mysql_express_javascript_app_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /tmp/sequelize_mysql_express_javascript_app:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sequelize_mysql_express_javascript_app_db_name
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - sequelize_mysql_express_javascript_app
    restart: always
    ports:
      - '3306:3306'

networks:
  sequelize_mysql_express_javascript_app:
    driver: bridge
